import { Candidate, Interview } from './models';

export const usersData = [
  { id: 1, name: 'Admin System', username: 'admin', password: 'admin123', role: 'Admin' },
  { id: 2, name: 'Sarah Malik', username: 'sarah', password: 'sarah123', role: 'Interviewer' },
  { id: 3, name: 'Daniel Shah', username: 'daniel', password: 'daniel123', role: 'Interviewer' },
  { id: 4, name: 'Ali Hassan', username: 'ali', password: 'ali123', role: 'Interviewer' },
  { id: 5, name: 'Ahmed Khan', username: 'ahmed', password: 'ahmed123', role: 'Interviewer' },
  { id: 6, name: 'Aisha Noor', username: 'aisha', password: 'aisha123', role: 'Interviewer' },
  { id: 7, name: 'Michael Reed', username: 'michael', password: 'michael123', role: 'Interviewer' }
];

export const candidatesData: Candidate[] = [
  { id: 1, name: 'Leo Brooks', role: 'AI/ML Engineer', company: 'VertexSoft', department: 'Engineering', experience: '4 Years', appliedDate: '2025-01-15', status: 'Interviewing' },
  { id: 2, name: 'Olivia Hayes', role: 'AI/ML Engineer', company: 'VertexSoft', department: 'Engineering', experience: '3 Years', appliedDate: '2025-01-05', status: 'Screening' },
  { id: 3, name: 'Ava Reed', role: 'AI/ML Engineer', company: 'CloudNest', department: 'Engineering', experience: '5 Years', appliedDate: '2025-02-20', status: 'Offer Sent' },
  { id: 4, name: 'Grace Reed', role: 'Python Developer', company: 'ABC Tech', department: 'Engineering', experience: '2 Years', appliedDate: '2025-02-27', status: 'Offer Sent' },
  { id: 5, name: 'Henry Turner', role: '.NET Developer', company: 'Future Labs', department: 'Engineering', experience: '6 Years', appliedDate: '2025-04-21', status: 'Rejected' },
  { id: 6, name: 'Olivia Murphy', role: 'DevOps Engineer', company: 'Future Labs', department: 'Engineering', experience: '4 Years', appliedDate: '2025-01-05', status: 'Draft' },
  { id: 7, name: 'Leo Hayes', role: 'React Developer', company: 'Nova Systems', department: 'Engineering', experience: '3 Years', appliedDate: '2025-04-26', status: 'Interviewing' },
  { id: 8, name: 'Jack Hayes', role: 'QA Engineer', company: 'ABC Tech', department: 'Engineering', experience: '5 Years', appliedDate: '2025-05-29', status: 'Screening' },
  { id: 9, name: 'Ethan Murphy', role: 'AI/ML Engineer', company: 'ABC Tech', department: 'Engineering', experience: '2 Years', appliedDate: '2025-03-12', status: 'Rejected' },
  { id: 10, name: 'Ethan Cole', role: 'Python Developer', company: 'Nova Systems', department: 'Engineering', experience: '7 Years', appliedDate: '2025-03-05', status: 'Draft' },
  { id: 11, name: 'Ella Brooks', role: 'React Developer', company: 'TechBridge', department: 'Engineering', experience: '4 Years', appliedDate: '2025-02-27', status: 'Interviewing' },
  { id: 12, name: 'Leo Brooks', role: 'AI/ML Engineer', company: 'CloudNest', department: 'Engineering', experience: '3 Years', appliedDate: '2025-06-24', status: 'Rejected' },
  { id: 13, name: 'Ethan Ward', role: '.NET Developer', company: 'VertexSoft', department: 'Engineering', experience: '6 Years', appliedDate: '2025-03-23', status: 'Rejected' },
  { id: 14, name: 'Ethan Turner', role: 'Python Developer', company: 'BluePeak', department: 'Engineering', experience: '4 Years', appliedDate: '2025-01-24', status: 'Rejected' },
  { id: 15, name: 'Liam Turner', role: 'React Developer', company: 'TechBridge', department: 'Engineering', experience: '2 Years', appliedDate: '2025-05-11', status: 'Rejected' },
  { id: 16, name: 'Zoe Parker', role: 'AI/ML Engineer', company: 'ABC Tech', department: 'Engineering', experience: '1 Year', appliedDate: '2025-01-01', status: 'Interviewing' },
  { id: 17, name: 'Mia Bennett', role: '.NET Developer', company: 'VertexSoft', department: 'Engineering', experience: '4 Years', appliedDate: '2025-01-07', status: 'Screening' },
  { id: 18, name: 'Grace Hayes', role: 'React Developer', company: 'Future Labs', department: 'Engineering', experience: '5 Years', appliedDate: '2025-06-19', status: 'Interviewing' },
  { id: 19, name: 'James Bennett', role: 'AI/ML Engineer', company: 'TechBridge', department: 'Engineering', experience: '4 Years', appliedDate: '2025-05-07', status: 'Draft' },
  { id: 20, name: 'Grace Bennett', role: '.NET Developer', company: 'TechBridge', department: 'Engineering', experience: '6 Years', appliedDate: '2025-06-10', status: 'Interviewing' },
  { id: 21, name: 'Lucas Turner', role: 'React Developer', company: 'Future Labs', department: 'Engineering', experience: '3 Years', appliedDate: '2026-07-01', status: 'Interviewing' },
  { id: 22, name: 'Mia Cole', role: 'AI/ML Engineer', company: 'Future Labs', department: 'Engineering', experience: '5 Years', appliedDate: '2026-07-02', status: 'Interviewing' },
  { id: 23, name: 'Alex Rivera', role: 'UI/UX Designer', company: 'Nova Systems', department: 'Design', experience: '8 Years', appliedDate: '2026-07-05', status: 'Interviewing' },
  { id: 24, name: 'Isabella Taylor', role: 'Frontend Developer', company: 'TechBridge', department: 'Engineering', experience: '2 Years', appliedDate: '2025-08-11', status: 'Draft' },
  { id: 25, name: 'Mason Clark', role: 'Backend Developer', company: 'CloudNest', department: 'Engineering', experience: '5 Years', appliedDate: '2025-08-15', status: 'Screening' },
  { id: 26, name: 'Evelyn Wright', role: 'Full Stack Developer', company: 'Nova Systems', department: 'Engineering', experience: '7 Years', appliedDate: '2025-08-18', status: 'Interviewing' },
  { id: 27, name: 'Logan Scott', role: 'Product Manager', company: 'BluePeak', department: 'Product', experience: '6 Years', appliedDate: '2025-08-20', status: 'Screening' },
  { id: 28, name: 'Abigail Green', role: 'Data Scientist', company: 'VertexSoft', department: 'Data', experience: '4 Years', appliedDate: '2025-08-22', status: 'Interviewing' },
  { id: 29, name: 'Elijah Adams', role: 'Data Analyst', company: 'ABC Tech', department: 'Data', experience: '3 Years', appliedDate: '2025-08-25', status: 'Offer Sent' },
  { id: 30, name: 'Harper Baker', role: 'HR Manager', company: 'Future Labs', department: 'HR', experience: '8 Years', appliedDate: '2025-08-28', status: 'Screening' },
  { id: 31, name: 'Benjamin Gonzalez', role: 'Marketing Specialist', company: 'CloudNest', department: 'Marketing', experience: '2 Years', appliedDate: '2025-09-01', status: 'Draft' },
  { id: 32, name: 'Amelia Nelson', role: 'Sales Executive', company: 'TechBridge', department: 'Sales', experience: '5 Years', appliedDate: '2025-09-05', status: 'Interviewing' },
  { id: 33, name: 'Lucas Carter', role: 'UI/UX Designer', company: 'BluePeak', department: 'Design', experience: '4 Years', appliedDate: '2025-09-08', status: 'Rejected' },
  { id: 34, name: 'Charlotte Mitchell', role: 'Frontend Developer', company: 'VertexSoft', department: 'Engineering', experience: '3 Years', appliedDate: '2025-09-10', status: 'Screening' },
  { id: 35, name: 'Alexander Perez', role: 'Backend Developer', company: 'Nova Systems', department: 'Engineering', experience: '6 Years', appliedDate: '2025-09-12', status: 'Interviewing' },
  { id: 36, name: 'Emily Roberts', role: 'Full Stack Developer', company: 'ABC Tech', department: 'Engineering', experience: '5 Years', appliedDate: '2025-09-15', status: 'Offer Sent' },
  { id: 37, name: 'Daniel Turner', role: 'Product Manager', company: 'Future Labs', department: 'Product', experience: '7 Years', appliedDate: '2025-09-18', status: 'Screening' },
  { id: 38, name: 'Madison Phillips', role: 'Data Scientist', company: 'TechBridge', department: 'Data', experience: '3 Years', appliedDate: '2025-09-20', status: 'Draft' },
  { id: 39, name: 'Matthew Campbell', role: 'Data Analyst', company: 'CloudNest', department: 'Data', experience: '2 Years', appliedDate: '2025-09-22', status: 'Interviewing' },
  { id: 40, name: 'Elizabeth Parker', role: 'HR Manager', company: 'BluePeak', department: 'HR', experience: '9 Years', appliedDate: '2025-09-25', status: 'Screening' },
  { id: 41, name: 'Joseph Evans', role: 'Marketing Specialist', company: 'VertexSoft', department: 'Marketing', experience: '4 Years', appliedDate: '2025-09-28', status: 'Rejected' },
  { id: 42, name: 'Sofia Edwards', role: 'Sales Executive', company: 'Nova Systems', department: 'Sales', experience: '6 Years', appliedDate: '2025-10-01', status: 'Interviewing' },
  { id: 43, name: 'David Collins', role: 'UI/UX Designer', company: 'ABC Tech', department: 'Design', experience: '5 Years', appliedDate: '2025-10-05', status: 'Screening' },
  { id: 44, name: 'Avery Stewart', role: 'Frontend Developer', company: 'Future Labs', department: 'Engineering', experience: '2 Years', appliedDate: '2025-10-08', status: 'Draft' },
  { id: 45, name: 'Samuel Sanchez', role: 'Backend Developer', company: 'TechBridge', department: 'Engineering', experience: '7 Years', appliedDate: '2025-10-10', status: 'Interviewing' },
  { id: 46, name: 'Chloe Morris', role: 'Full Stack Developer', company: 'CloudNest', department: 'Engineering', experience: '4 Years', appliedDate: '2025-10-12', status: 'Offer Sent' },
  { id: 47, name: 'Carter Rogers', role: 'Product Manager', company: 'BluePeak', department: 'Product', experience: '8 Years', appliedDate: '2025-10-15', status: 'Screening' },
  { id: 48, name: 'Grace Reed', role: 'Data Scientist', company: 'VertexSoft', department: 'Data', experience: '5 Years', appliedDate: '2025-10-18', status: 'Interviewing' },
  { id: 49, name: 'John Cook', role: 'Data Analyst', company: 'Nova Systems', department: 'Data', experience: '3 Years', appliedDate: '2025-10-20', status: 'Draft' },
  { id: 50, name: 'Lily Morgan', role: 'HR Manager', company: 'ABC Tech', department: 'HR', experience: '6 Years', appliedDate: '2025-10-25', status: 'Screening' }
];

export const interviewsData: Interview[] = [
  { id: 'int_1', candidateId: 1, interviewerName: 'Sarah Malik', date: '2025-02-10', time: '10:00 AM', status: 'Completed', feedback: { rating: 4.2, positive: 'Hands-on with core concepts', negative: 'Average database knowledge', additional: 'Good cultural fit', recommended: 'No' }, hiringUpdate: 'Proceed to Round 2' },
  { id: 'int_2', candidateId: 2, interviewerName: 'Daniel Shah', date: '2025-01-09', time: '14:00 PM', status: 'Completed', feedback: { rating: 3, positive: 'Good communication', negative: 'Could improve coding standards', additional: 'Good cultural fit', recommended: 'Hold' }, hiringUpdate: 'Proceed to Round 2' },
  { id: 'int_3', candidateId: 3, interviewerName: 'Ali Hassan', date: '2025-03-06', time: '09:00 AM', status: 'Completed', feedback: { rating: 3.2, positive: 'Strong problem-solving skills', negative: 'Limited testing experience', additional: '', recommended: 'Hold' }, hiringUpdate: 'Offer recommended' },
  { id: 'int_4', candidateId: 4, interviewerName: 'Ahmed Khan', date: '2025-02-27', time: '11:00 AM', status: 'Completed', feedback: { rating: 2.2, positive: 'Good API knowledge', negative: 'Needs better communication', additional: 'Requires mentoring', recommended: 'Hold' }, hiringUpdate: 'Offer recommended' },
  { id: 'int_5', candidateId: 5, interviewerName: 'Aisha Noor', date: '2025-04-21', time: '16:00 PM', status: 'Completed', feedback: { rating: 1.7, positive: 'Clean coding style', negative: 'Limited testing experience', additional: 'Good cultural fit', recommended: 'No' }, hiringUpdate: 'Offer recommended' },
  { id: 'int_6', candidateId: 11, interviewerName: 'Michael Reed', date: '2025-02-27', time: '10:00 AM', status: 'Completed', feedback: { rating: 1.6, positive: 'Hands-on with core concepts', negative: 'Weak system design', additional: 'Potential candidate', recommended: 'Hold' }, hiringUpdate: 'Proceed to Round 2' },
  { id: 'int_7', candidateId: 18, interviewerName: 'Ahmed Khan', date: '2025-06-19', time: '13:00 PM', status: 'Completed', feedback: { rating: 4.9, positive: 'Quick learner', negative: 'Needs better communication', additional: '', recommended: 'No' }, hiringUpdate: 'Proceed to Round 2' },
  { id: 'int_8', candidateId: 19, interviewerName: 'Daniel Shah', date: '2025-05-07', time: '15:00 PM', status: 'Completed', feedback: { rating: 3.8, positive: 'Quick learner', negative: 'Average database knowledge', additional: 'Potential candidate', recommended: 'Hold' }, hiringUpdate: 'Await final decision' },
  { id: 'int_9', candidateId: 20, interviewerName: 'Aisha Noor', date: '2025-06-10', time: '11:00 AM', status: 'Completed', feedback: { rating: 2.7, positive: 'Clean coding style', negative: 'Weak system design', additional: 'Potential candidate', recommended: 'Hold' }, hiringUpdate: 'Proceed to Round 2' },
  // Future Upcoming
  { id: 'int_10', candidateId: 21, interviewerName: 'Daniel Shah', date: '2026-07-20', time: '09:00 AM', status: 'Scheduled' },
  { id: 'int_11', candidateId: 22, interviewerName: 'Ahmed Khan', date: '2026-07-21', time: '14:00 PM', status: 'Scheduled' },
  { id: 'int_12', candidateId: 23, interviewerName: 'Sarah Malik', date: '2026-07-24', time: '10:00 AM', status: 'Scheduled' }
];
